# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="church-community-builder"

plugins=(
  git
  osx
  brew
  bundler
  gem
  github
  history-substring-search
  zsh-syntax-highlighting
  vi-mode
)

source $ZSH/oh-my-zsh.sh

alias g="jump"
alias s="bookmark"
alias d="deletemark"
alias p="showmarks"
alias l="showmarks"
