# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME=robbyrussell

plugins=(
  git
  osx
  brew
  bundler
  gem
  github
  history-substring-search
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
